In [1]:
import numpy as np

---
### numpy.empty 
#### numpy.empty(shape, dtype=float, order='C') 
* Devuelve una nueva matriz de forma y tipo dados, sin inicializar las entradas.
---

In [2]:
np.empty((2,2))

array([[ 2.22809558e-312,  2.14321575e-312],
       [-4.34376063e-311,  2.00390437e+000]])

---

In [3]:
np.empty((2,2), dtype=int)

array([[       450971566180,        433791697010],
       [      8791869391117, 4611694810296837088]])

In [4]:
np.empty((2,2), dtype=float)

array([[ 2.22809558e-312,  2.14321575e-312],
       [-4.34376063e-311,  2.00390437e+000]])

---
### numpy.empty_like 
#### numpy.empty_like(prototipo ,dtype=Ninguno, orden='K', subok=Verdadero) 
* Devuelve una nueva matriz con la misma forma y tipo que una matriz dada.
---

In [5]:
a = ((1,2,3), (4,5,6))

In [6]:
a

((1, 2, 3), (4, 5, 6))

In [7]:
np.empty_like(a)

array([[                  0, 3631082602014849125, 3630291838406506544],
       [7364623648683287346, 3991426466123495732, 3774970182577502513]])

In [8]:
a = np.array(((1.,2,3), (4,5,6)))

In [9]:
np.empty_like(a)

array([[0., 0., 0.],
       [0., 0., 0.]])

In [10]:
np.empty_like(a, dtype=int)

array([[0, 0, 0],
       [0, 0, 0]])

---
### numpy.eye 
#### numpy.eye(N, M=Ninguna, k=0, dtype=<clase'float'>, orden='C')

* Devuelva una matriz bidimensional con unas en diagonal y ceros en otra parte.
---

In [11]:
np.eye(2, dtype=int)

array([[1, 0],
       [0, 1]])

In [12]:
np.eye(4, dtype=float)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [13]:
np.eye(3, k=1) #Desplaza en 0 la diagonal

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [14]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [15]:
np.eye(4, k=2) # Desplaza dos posiciones la diagonal

array([[0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

---
### numpy.identity 
#### numpy.identity(n, dtype=Ninguno)
* Devuelve la matriz de identidad.
* La matriz de identidad es una matriz cuadrada con unas en la diagonal principal.
---


In [16]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [17]:
np.all(np.identity(3) == np.eye(3))

True

In [18]:
np.identity(3) == np.eye(3)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

---
### numpy.ones 
#### numpy.ones(shape, dtype=None, order='C')
* Devuelve un nuevo conjunto de formas y tipos dados, llenos de unos.
---



In [19]:
np.ones(5)

array([1., 1., 1., 1., 1.])

---

In [20]:
np.ones((5,), dtype=int)

array([1, 1, 1, 1, 1])

---

In [21]:
np.ones((2,1))

array([[1.],
       [1.]])

---

In [22]:
s=(2,2)

In [23]:
np.ones(s)

array([[1., 1.],
       [1., 1.]])

---
### np.ones_like 
#### np.ones_like(a, dtype=Ninguno, orden='K', subok=Verdadero)
* Devuelve una matriz de unidades con la misma forma y tipo que una matriz dada.
---

In [24]:
x = np.arange(6)

In [25]:
x = x.reshape((2,3))

In [26]:
x

array([[0, 1, 2],
       [3, 4, 5]])

In [27]:
np.ones_like(x)

array([[1, 1, 1],
       [1, 1, 1]])

---

In [28]:
y = np.arange(3, dtype=float)

In [29]:
y

array([0., 1., 2.])

In [30]:
np.ones_like(y)

array([1., 1., 1.])

---
### np.zeros 
#### np.zeros(shape, dtype=float, order='C') 
* Devuelve una nueva matriz de forma y tipo dado, rellena con ceros.
---

In [31]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

---

In [32]:
np.zeros((5,), dtype=int)

array([0, 0, 0, 0, 0])

---

In [33]:
np.zeros((2,1))

array([[0.],
       [0.]])

---

In [34]:
s=(2,2)

In [35]:
np.zeros(s)

array([[0., 0.],
       [0., 0.]])

---

In [36]:
np.zeros((2,), dtype=[("x", "i4"), ("y", "i4")])

array([(0, 0), (0, 0)], dtype=[('x', '<i4'), ('y', '<i4')])

---
### numpy.zeros_like 
#### numpy.zeros_like( a , dtype = Ninguno , orden = 'K' , subok = Verdadero ) [fuente]
* Devuelve una matriz de ceros con la misma forma y tipo que una matriz dada.
---



In [37]:
x = np.arange(6)

In [38]:
x = x.reshape((2,3))

In [39]:
x

array([[0, 1, 2],
       [3, 4, 5]])

In [40]:
np.zeros_like(x)

array([[0, 0, 0],
       [0, 0, 0]])

---

In [41]:
y = np.arange(3, dtype=float)

In [42]:
y

array([0., 1., 2.])

In [43]:
np.zeros_like(y)

array([0., 0., 0.])

---
### numpy.full 
#### numpy.full( shape , fill_value , dtype = None , order = 'C' ) [fuente]
* Devuelve una nueva matriz de forma y tipo dado, rellenada con fill_value .
---

In [44]:
np.full((2,2), np.inf)

array([[inf, inf],
       [inf, inf]])

In [45]:
np.full((2,2), 10)

array([[10, 10],
       [10, 10]])

---
### numpy.full_like 
#### numpy.full_like( a , fill_value , dtype = None , order = 'K' , subok = True ) [fuente]
* Devuelve una matriz completa con la misma forma y tipo que una matriz dada.
---

In [46]:
x = np.arange(6, dtype=int)

In [47]:
np.full_like(x, 1)

array([1, 1, 1, 1, 1, 1])

In [48]:
np.full_like(x, 0.1)

array([0, 0, 0, 0, 0, 0])

In [49]:
np.full_like(x, 0.11, dtype=np.double)

array([0.11, 0.11, 0.11, 0.11, 0.11, 0.11])

In [50]:
np.full_like(x, np.nan, dtype=np.double)

array([nan, nan, nan, nan, nan, nan])

---

In [51]:
y = np.arange(6, dtype=np.double)

In [52]:
np.full_like(y, 0.1)


array([0.1, 0.1, 0.1, 0.1, 0.1, 0.1])