In [1]:
import numpy as np

---
### np.array 
#### np.array(objeto, dtype=None, copy=True, orden='K', subok=False, ndmin=0)
 - Crear una matriz.
---

In [2]:
np.array([1,2,3])

array([1, 2, 3])

* Upcasting:
---

In [3]:
np.array([1,2,3.0])

array([1., 2., 3.])

* Mas de una dimensión
---

In [4]:
np.array([[1,2], [3,4]])

array([[1, 2],
       [3, 4]])

* Dimensiones Minimas 2:
---

In [5]:
np.array([1,2,3], ndmin=2)

array([[1, 2, 3]])

* Tipo proporcionado:
---

In [6]:
np.array([1,2,3], dtype=complex)

array([1.+0.j, 2.+0.j, 3.+0.j])

* Tipo de datos que consta de más de un elemento:
---

In [7]:
x = np.array([(1,2), (3,4)], dtype=[("a", "<i4"), ("b", "<i4")])

* Creando una matriz a partir de subclases:
---

In [8]:
np.mat("1 2 ; 3 4")

matrix([[1, 2],
        [3, 4]])

In [9]:
np.array(np.mat("1 2; 3 4"))

array([[1, 2],
       [3, 4]])

---

In [10]:
np.array(np.mat("1 2 ; 3 4"), subok=True)

matrix([[1, 2],
        [3, 4]])

---
### np.asarray 
#### np.asarray(a, dtype=None, orden=None)
* Convertir la entrada a una matriz.
---


* Convertir una lista en una matriz
---

In [11]:
a = [1, 2]

In [12]:
np.asarray(a)

array([1, 2])

* Las matrices existentes no se copian
---

In [13]:
a = np.array([1, 2])

In [14]:
np.asarray(a) is a

True

* Si dtype se establece, la matriz se copia solo si dtype no coincide:
---

In [15]:
a = np.array([1, 2], dtype=np.float32)

In [16]:
np.asarray(a, dtype=np.float32) is a

True

In [17]:
np.asarray(a, dtype=np.float64) is a

False

* Contrariamente a asanyarray, las subclases ndarray no se pasan a través de:
---

In [18]:
issubclass (np.recarray, np.ndarray)

True

In [19]:
a = np.array([(1., 2), (3, 4)], dtype="f4, i4").view(np.recarray)

In [20]:
a

rec.array([(1., 2), (3., 4)],
          dtype=[('f0', '<f4'), ('f1', '<i4')])

In [21]:
np.asarray(a) is a

False

In [22]:
np.asanyarray(a) is a

True

---
### np.asanyarray 
#### np.asanyarray(a, dtype=Ninguno, orden=Ninguno)
* Convierte la entrada a un ndarray, pero pase las subclases a través de ndarray.
---

* Convertir una lista en un array
---

In [23]:
a = [1, 2]

In [24]:
a

[1, 2]

In [25]:
np.asanyarray(a)

array([1, 2])

* Las instancias de las ndarray subclases se pasan como está:
---

In [26]:
a = np.array([(1, 2), (3, 4)], dtype="f4, i4").view(np.recarray)

In [27]:
a

rec.array([(1., 2), (3., 4)],
          dtype=[('f0', '<f4'), ('f1', '<i4')])

In [28]:
np.asanyarray(a) is a

True

---
### np.ascontiguousarray 
#### np.ascontiguousarray(a, dtype=Ninguno)
* Devuelve una matriz contigua (ndim> = 1) en la memoria (orden C).
---

In [29]:
x = np.arange(6).reshape(2,3)

In [30]:
x

array([[0, 1, 2],
       [3, 4, 5]])

In [31]:
np.ascontiguousarray(x, dtype=np.float32)

array([[0., 1., 2.],
       [3., 4., 5.]], dtype=float32)

In [32]:
x.flags["C_CONTIGUOUS"]

True

---
### np.asmatrix 
#### np.asmatrix(data, dtype=None)

* Interpreta la entrada como una matriz.
---

In [33]:
x = np.array([[1, 2], [3, 4]])

In [34]:
x

array([[1, 2],
       [3, 4]])

---

In [35]:
m = np.asmatrix(x)

In [36]:
m

matrix([[1, 2],
        [3, 4]])

---

In [37]:
x[0, 0] = 5

---

In [38]:
m

matrix([[5, 2],
        [3, 4]])

---
np.copy 
np.copy(a, orden='K')

* Devuelve una copia de matriz del objeto dado.
---

In [39]:
a

rec.array([(1., 2), (3., 4)],
          dtype=[('f0', '<f4'), ('f1', '<i4')])

In [40]:
np.array(a, copy=True)

array([(1., 2), (3., 4)],
      dtype=(numpy.record, [('f0', '<f4'), ('f1', '<i4')]))

---

In [41]:
x = np.array([1, 2, 3])

In [42]:
x

array([1, 2, 3])

In [43]:
y = x

In [44]:
y

array([1, 2, 3])

In [45]:
z = np.copy(x)

---

In [46]:
x[0] = 10

In [47]:
x[0] == y[0]

True

In [48]:
x[0] == z[0]

False

---
### np.frombuffer 
#### np.frombuffer(buffer, dtype=float, count=-1 ,offset=0) 
* Interpreta un búfer como una matriz unidimensional.
---

In [49]:
dt = np.dtype(int)

In [50]:
dt = dt.newbyteorder(">")

In [51]:
np.frombuffer(buf, dtype=dt)

NameError: name 'buf' is not defined

In [ ]:
s = 'hello world'

In [ ]:
s

In [ ]:
np.frombuffer(s, dtype='S1', count=5, offset=6)

---

In [ ]:
np.frombuffer(b'\x01\x02', dtype=np.uint8)

In [ ]:
np.frombuffer(b'\x01\x02\x03\x04\x05', dtype=np.uint8, count=3)

---
### np.fromfile 
#### np.fromfile (a, dtype=float, count=-1, sep='') 
* Construye una matriz a partir de datos en un archivo de texto o binario.

* Una forma altamente eficiente de leer datos binarios con un tipo de datos conocido, así como analizar archivos de texto con formato simple. Los datos escritos usando el método tofile se pueden leer usando esta función.
---

* Construyendo un ndarray
---

In [ ]:
dt = np.dtype([("time", [("min", int), ("sec", int)]),
              ("temp", float)])

In [ ]:
dt

In [ ]:
x = np.zeros((1,), dtype=dt)

In [ ]:
x

In [ ]:
x["time"]["min"] = 10; x["temp"] = 98.25

In [ ]:
x

---
### np.fromfunction 
#### np.fromfunction( función , forma , ** kwargs ) [fuente]
* Construye una matriz ejecutando una función sobre cada coordenada.
* La matriz resultante, por lo tanto, tiene un valor en coordenada .fn(x, y, z)(x, y, z)
---

In [ ]:
np.fromfunction(lambda i, j: i == j, (3,3), dtype=int)

---

In [ ]:
np.fromfunction(lambda i, j: i+j, (3,3), dtype=int)

---
### numpy.fromiter 
#### numpy.fromiter( iterable , dtype , count = -1 ) 
* Crea una nueva matriz unidimensional a partir de un objeto iterable.
---

In [ ]:
iterable = (x*x for x in range(5))

In [ ]:
np.fromiter(iterable, float)

---
### numpy.fromstring 
#### numpy.fromstring( string , dtype = float , count = -1 , sep = '' ) 
* Una nueva matriz 1-D inicializada a partir de datos de texto en una cadena.
---

In [ ]:
np.fromstring("1 2", dtype=int, sep=" ")

In [ ]:
np.fromstring("1 ,2", dtype= int, sep=",")

---
### numpy.loadtxt 
##### ny.loadtxt(Fname, dtype=<clase'float'>, comentarios='#' ,delimitador=None , convertidores=None, skiprows=0, usecols=None, desempaquetar=False, ndmin=0, encoding='bytes', MAX_ROWS=None)
* Cargar datos desde un archivo de texto.
---


In [ ]:
from io import StringIO

In [ ]:
c = StringIO(u"0 1\n2 3")

In [ ]:
np.loadtxt(c)

---

In [ ]:
d = StringIO(u"M 21. 72\nF 35 58")

In [ ]:
np.loadtxt(d, dtype={"names": ("gender", "age", "weight"),
                    "formats": ("S1", "i4", "f4")})

---

In [ ]:
c = StringIO(u"1,0,2\n3,0,4")

In [ ]:
x , y = np.loadtxt(c, delimiter=",", usecols=(0,2), unpack=True)

In [ ]:
x

In [ ]:
y