In [1]:
import numpy as np

---
#### ny.core.records.array 
#### ny.core.records.array( obj , dtype = None , forma = None , offset = 0 , strides = None , formatos = None , nombres = None , títulos = None , alineado = False , byteorder = None , copy = True )
* Construye una matriz de grabación a partir de una gran variedad de objetos.
---


* Sin Ejemplos
---

---
### numpy.core.records.fromarrays 
#### numpy.core.records.fromarrays( arrayList , dtype = Ninguno , forma = Ninguno , formatos = Ninguno , nombres = Ninguno , títulos = Ninguno , alineado = Falso , orden de bytes = Ninguno ) [fuente]
* crear una matriz de registros a partir de una lista (plana) de matrices
---

In [2]:
x1 = np.array([1, 2, 3, 4])

In [3]:
x2 = np.array(["a", "dd", "xyz", "12"])

In [4]:
x3 = ([1.1, 2, 3, 4])

In [5]:
r = np.core.records.fromarrays([x1, x2, x3], names="a,b,c")

In [6]:
r

rec.array([(1, 'a', 1.1), (2, 'dd', 2. ), (3, 'xyz', 3. ), (4, '12', 4. )],
          dtype=[('a', '<i8'), ('b', '<U3'), ('c', '<f8')])

In [7]:
print(r[1])

(2, 'dd', 2.)


In [8]:
x1[1] = 34

In [9]:
r.a

array([1, 2, 3, 4])

In [10]:
x1

array([ 1, 34,  3,  4])

---
### numpy.core.records.fromstring 
#### numpy.core.records.fromstring( datastring , dtype = Ninguno , forma = Ninguno , desplazamiento = 0 , formatos = Ninguno , nombres = Ninguno , títulos = Ninguno , alineado = Falso , orden de bytes = Ninguno )
* crear una matriz de registros (solo lectura) a partir de datos binarios contenidos en una cadena
---

* sin ejemplos
---

---
### numpy.core.records.fromrecords 
#### numpy.core.records.fromrecords( recList , dtype = Ninguno , forma = Ninguno , formatos = Ninguno , nombres = Ninguno , títulos = Ninguno , alineado = Falso , byteorder = Ninguno ) [fuente]
* crear un recarray de una lista de registros en forma de texto
---

In [11]:
r = np.core.records.fromrecords([(456, "dbe", 1.2), (2, "de", 1.3)], names="col1, col2, col3")

In [12]:
print(r[0])

(456, 'dbe', 1.2)


In [13]:
r.col1

array([456,   2])

In [14]:
r.col2

array(['dbe', 'de'], dtype='<U3')

In [15]:
import pickle

In [16]:
print(pickle.loads(pickle.dumps(r)))

[(456, 'dbe', 1.2) (  2, 'de', 1.3)]


---
### numpy.core.records.fromfile 
#### numpy.core.records.fromfile( fd , dtype = Ninguno , forma = Ninguno , desplazamiento = 0 , formatos = Ninguno , nombres = Ninguno , títulos = Ninguno , alineado = Falso , orden de bytes = Ninguno ) [fuente]
* Crear una matriz de datos de archivos binarios
---

In [17]:
from tempfile import TemporaryFile

In [18]:
a = np.empty(10, dtype="f8,i4,a5")

In [19]:
a[5] = (0.5, 10, "bcde")

In [20]:
a

array([(1.18575755e-322,          0, b''),
       (0.00000000e+000,          0, b''),
       (0.00000000e+000,          0, b''),
       (0.00000000e+000,          0, b''),
       (0.00000000e+000,          0, b''),
       (5.00000000e-001,         10, b'bcde'),
       (1.12101221e-047,      13157, b''),
       (1.02765654e-321, 1627394256, b'me":"'),
       (7.86273067e+199, 1751347054, b'et","'),
       (4.27255699e+180, 1696741922, b'xecut')],
      dtype=[('f0', '<f8'), ('f1', '<i4'), ('f2', 'S5')])

In [21]:
a[5]

(0.5, 10, b'bcde')

In [22]:
a[0]

(1.2e-322, 0, b'')

In [23]:
fd = TemporaryFile()

In [24]:
a = a.newbyteorder("<")

In [25]:
a.tofile(fd)

In [26]:
fd.seek(0)

0

In [27]:
r = np.core.records.fromfile(fd, formats="f8, i4, a5", shape=10, byteorder="<")

In [28]:
print(r[5])

(0.5, 10, b'bcde')


In [29]:
r.shape


(10,)