In [1]:
import numpy as np

---
### numpy.diag 
#### numpy.diag( v , k = 0 ) [fuente]
* Extrae una diagonal o construye una matriz diagonal.
---

In [2]:
x = np.arange(9).reshape((3,3))

In [3]:
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

---

In [10]:
np.diag(x) # Extrae solo la diagonal

array([0, 4, 8])

In [11]:
np.diag(x, k=1) # extre l diagonal con 0 desplazadado en +1

array([1, 5])

In [9]:
np.diag(x, k=-1)

array([3, 7])

---

In [6]:
np.diag(np.diag(x))

array([[0, 0, 0],
       [0, 4, 0],
       [0, 0, 8]])

In [21]:
np.diag(np.diag(x, k=0))

array([[0, 0, 0],
       [0, 4, 0],
       [0, 0, 8]])

---
### numpy.diagflat 
#### numpy.diagflat( v , k = 0 ) [fuente]
* Cree una matriz bidimensional con la entrada aplanada como una diagonal.
---

In [22]:
np.diagflat([[1, 2], [3, 4]])

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

---

In [23]:
np.diagflat([1, 2], 1)

array([[0, 1, 0],
       [0, 0, 2],
       [0, 0, 0]])

---
### numpy.tri 
#### numpy.tri( N , M = Ninguna , k = 0 , dtype = <clase 'float'> ) [fuente]
* Una matriz con unos en y por debajo de la diagonal dada y ceros en otros lugares.
---

In [24]:
np.tri(3, 5, 2, dtype=int)

array([[1, 1, 1, 0, 0],
       [1, 1, 1, 1, 0],
       [1, 1, 1, 1, 1]])

---

In [25]:
np.tri(3, 5, -1)

array([[0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [1., 1., 0., 0., 0.]])

---
### numpy.tril 
#### numpy.tril( m , k = 0 ) [fuente]
* Triángulo inferior de una matriz.
---

In [29]:
np.tril([[1,2,3],[4,5,6],[7,8,9],[10,11,12]], -1)

array([[ 0,  0,  0],
       [ 4,  0,  0],
       [ 7,  8,  0],
       [10, 11, 12]])

In [32]:
np.tril([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15]], 0)

array([[ 1,  0,  0],
       [ 4,  5,  0],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

---
### numpy.triu 
#### numpy.triu( m , k = 0 ) [fuente]
* Triángulo superior de una matriz.
---

In [33]:
np.triu([[1,2,3],[4,5,6],[7,8,9],[10,11,12]], -1)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 0,  8,  9],
       [ 0,  0, 12]])

---
### numpy.vander 
#### numpy.vander( x , N = Ninguna , aumentando = Falso ) [fuente]
* Generar una matriz de vandermonde.
---

In [39]:
x = np.array([1,2,3,5,6])

In [40]:
n= 4

In [41]:
np.vander(x, n)

array([[  1,   1,   1,   1],
       [  8,   4,   2,   1],
       [ 27,   9,   3,   1],
       [125,  25,   5,   1],
       [216,  36,   6,   1]])

---

In [42]:
np.column_stack([x**(n-1-i) for i in range(n)])

array([[  1,   1,   1,   1],
       [  8,   4,   2,   1],
       [ 27,   9,   3,   1],
       [125,  25,   5,   1],
       [216,  36,   6,   1]])

---

In [50]:
x = np.array([1,2,3,5])

In [51]:
np.vander(x)

array([[  1,   1,   1,   1],
       [  8,   4,   2,   1],
       [ 27,   9,   3,   1],
       [125,  25,   5,   1]])

In [52]:
np.vander(x, increasing=True)

array([[  1,   1,   1,   1],
       [  1,   2,   4,   8],
       [  1,   3,   9,  27],
       [  1,   5,  25, 125]])

---

In [53]:
np.linalg.det(np.vander(x))

48.00000000000003

In [54]:
(5-3)*(5-2)*(5-1)*(3-2)*(3-1)*(2-1)

48