In [1]:
import numpy as np

---
### numpy.mat 
#### numpy.mat( data , dtype = None ) [fuente]
* Interpreta la entrada como una matriz.
---

In [2]:
x = np.array([[1, 2], [3, 4]])

In [3]:
m = np.asmatrix(x)


In [4]:
x[0,0]=5

In [5]:
m

matrix([[5, 2],
        [3, 4]])

---
### numpy.bmat 
#### numpy.bmat( obj , ldict = None , gdict = None ) [fuente]
* Cree un objeto de matriz a partir de una cadena, secuencia anidada o matriz.
---

In [10]:
a = np.mat("1 1; 1 1")

In [11]:
b = np.mat("2 2 ; 2 2")

In [12]:
c = np.mat("3 4; 5 6")

In [13]:
d = np.mat("7 8; 9 0")

---

In [14]:
np.bmat([[a, b], [c, d]])

matrix([[1, 1, 2, 2],
        [1, 1, 2, 2],
        [3, 4, 7, 8],
        [5, 6, 9, 0]])

In [15]:
np.bmat(np.r_[np.c_[a, b], np.c_[c, d]])

matrix([[1, 1, 2, 2],
        [1, 1, 2, 2],
        [3, 4, 7, 8],
        [5, 6, 9, 0]])

In [17]:
np.bmat("a, b ; c, d")

matrix([[1, 1, 2, 2],
        [1, 1, 2, 2],
        [3, 4, 7, 8],
        [5, 6, 9, 0]])