In [1]:
import pandas as pd
import numpy as np
import matplotlib as ptl

In [2]:
index=pd.date_range("1/1/2019", periods=8)

In [3]:
s=pd.Series(np.random.randn(5), index=["a","b","c","d","e"])

In [4]:
df=pd.DataFrame(np.random.randn(8,3), index=index, columns=["A", "B", "C"])

In [5]:
wp=pd.Panel(np.random.randn(2,5,4), items=["Item1","Item2"], major_axis=pd.date_range("1/1/2000", periods=5), minor_axis=["A","B","C","D"])

/Users/camilopinochet/anaconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py:3267: FutureWarning: 
Panel is deprecated and will be removed in a future version.
The recommended way to represent these types of 3-dimensional data are with a MultiIndex on a DataFrame, via the Panel.to_frame() method
Alternatively, you can use the xarray package http://xarray.pydata.org/en/stable/.
Pandas provides a `.to_xarray()` method to help automate this conversion.

  exec(code_obj, self.user_global_ns, self.user_ns)


In [6]:
df

A         B         C
2019-01-01  0.969270  1.172040 -1.690689
2019-01-02  0.409140  1.176228 -0.920223
2019-01-03 -1.452269  1.901328  1.533538
2019-01-04  0.186764  1.941954 -1.064475
2019-01-05  1.862494 -0.939244  0.501686
2019-01-06 -1.629430  0.027949  0.683903
2019-01-07  1.166164  0.052193  0.860868
2019-01-08 -0.533773 -1.025914 -0.068835

In [7]:
long_series=pd.Series(np.random.randn(1000))

In [8]:
long_series.head()

0   -0.222759
1   -2.309752
2    0.091137
3   -0.204310
4    1.221907
dtype: float64

In [9]:
long_series.tail()

995    1.132131
996    0.027237
997    0.679194
998    0.112080
999   -2.181161
dtype: float64

In [10]:
df[:2]

A         B         C
2019-01-01  0.96927  1.172040 -1.690689
2019-01-02  0.40914  1.176228 -0.920223

In [11]:
df.columns=[x.lower() for x in df.columns]
df

a         b         c
2019-01-01  0.969270  1.172040 -1.690689
2019-01-02  0.409140  1.176228 -0.920223
2019-01-03 -1.452269  1.901328  1.533538
2019-01-04  0.186764  1.941954 -1.064475
2019-01-05  1.862494 -0.939244  0.501686
2019-01-06 -1.629430  0.027949  0.683903
2019-01-07  1.166164  0.052193  0.860868
2019-01-08 -0.533773 -1.025914 -0.068835

In [12]:
s.array

<PandasArray>
[ 0.4145250096848891,  1.5468897101177028, 0.47845927590848997,
 -0.8553892196185997,  -1.100573542680141]
Length: 5, dtype: float64

In [13]:
s.index.array

<PandasArray>
['a', 'b', 'c', 'd', 'e']
Length: 5, dtype: object

In [14]:
s.to_numpy()

array([ 0.41452501,  1.54688971,  0.47845928, -0.85538922, -1.10057354])

In [15]:
np.asarray(s)

array([ 0.41452501,  1.54688971,  0.47845928, -0.85538922, -1.10057354])

In [16]:
ser=pd.Series(pd.date_range("2000", periods=2, tz="CET"))

In [17]:
ser.to_numpy(dtype=object)

array([Timestamp('2000-01-01 00:00:00+0100', tz='CET', freq='D'),
       Timestamp('2000-01-02 00:00:00+0100', tz='CET', freq='D')],
      dtype=object)

In [18]:
ser.to_numpy(dtype="datetime64[ns]")

array(['1999-12-31T23:00:00.000000000', '2000-01-01T23:00:00.000000000'],
      dtype='datetime64[ns]')

In [19]:
df.to_numpy()

array([[ 0.9692703 ,  1.17204028, -1.69068891],
       [ 0.40913952,  1.17622846, -0.9202226 ],
       [-1.45226943,  1.90132801,  1.53353843],
       [ 0.18676404,  1.9419535 , -1.06447514],
       [ 1.8624936 , -0.93924436,  0.50168616],
       [-1.62943032,  0.0279491 ,  0.68390312],
       [ 1.16616437,  0.05219326,  0.86086844],
       [-0.53377289, -1.02591388, -0.06883456]])

In [20]:
df=pd.DataFrame({
                "one": pd.Series(np.random.randn(3), index=["a","b","c"]),
                "two": pd.Series(np.random.randn(4), index=["a","b","c","d"]),
                "three": pd.Series(np.random.randn(3), index=["b","c","d"]),
})

In [21]:
df

one       two     three
a -0.177935 -1.297314       NaN
b -0.516256  0.466938 -0.243861
c -0.736735 -0.356515 -0.598152
d       NaN  0.060768  0.309587

In [22]:
row = df.iloc[1]
row

one     -0.516256
two      0.466938
three   -0.243861
Name: b, dtype: float64

In [28]:
column=df["two"]

In [24]:
df.sub(row, axis="columns")

one       two     three
a  0.338321 -1.764252       NaN
b  0.000000  0.000000  0.000000
c -0.220479 -0.823453 -0.354292
d       NaN -0.406170  0.553447

In [25]:
df.sub(row, axis=1)

one       two     three
a  0.338321 -1.764252       NaN
b  0.000000  0.000000  0.000000
c -0.220479 -0.823453 -0.354292
d       NaN -0.406170  0.553447

In [26]:
df.sub(column, axis="index")

one  two     three
a  1.119379  0.0       NaN
b -0.983194  0.0 -0.710799
c -0.380221  0.0 -0.241638
d       NaN  0.0  0.248818

In [27]:
df.sub(column, axis=0)

one  two     three
a  1.119379  0.0       NaN
b -0.983194  0.0 -0.710799
c -0.380221  0.0 -0.241638
d       NaN  0.0  0.248818